env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
rules:
  indent:
    - warn
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
    - avoidEscape: true
  semi:
    - error
    - never
  eqeqeq:
    - error
    - smart
  "@typescript-eslint/no-empty-interface": off
  "@typescript-eslint/no-empty-function": off
  "@typescript-eslint/strict-boolean-expressions":
    - error
  "@typescript-eslint/no-namespace": off
